### ISSUE TITLE
Endereço é apagado quando a página de pagamento é atualizada

### ISSUE THREAD

**Issue by cledsonsilva** [r-martins/PagSeguro-Magento-Transparente-M2#101]
Quando atualizamos a página de pagamento, após já termos informado todo o endereço e já na tela de escolha da forma de pagamento, todos os dados de endereço são apagados. Isso ocorre quando o cliente compra como "visitante" (sem criar uma senha).

É ruim porque o cliente que optou por não criar uma conta/senha e atualizou a página de pagamento após inserir todo o endereço deverá voltar a página para poder reinserir o endereço, caso contrário a compra não é finalizada.

**Comment by r-martins** [comment]
Oi, Cledson. Tudo bom?
Este é o comportamento padrão do Magento, afinal temos podemos ter regras de desconto que afetariam o total do pedido e consequentemente as informações do form de pagamento (ex: parcelas).
Receio não ser um bug do módulo.

Me avise se entendi errado o problema.
Obrigado pelo contato de qualquer forma.
