### ISSUE TITLE
Não é possível fazer pagamento de produtos fracionados menores que 1 unidade

### ISSUE THREAD

**Issue by rodzappa** [r-martins/PagSeguro-Magento-Transparente-M2#102]
Se habilito no "Advanced Inventory" de um produto que sua unidade de comercialização aceita decimais e o valor mínimo para compra é de 0.5, por exemplo, o magento aceita montar o carrinho sem problemas.

Ao fazer o checkout usando qualquer meio de pagamento pelo módulo PagSeguro, o pagamento é abortado.
A seguinte mensagem aparece no system.log: 
``` 
[2021-11-11 19:43:00] main.CRITICAL: Placing an order with quote_id 208 is failed: Quantidade do item fora do permitido:  0 [] []
``` 
No frontend aparece: "Quantidade do item fora do permitido:  0"

Pagamentos via PayPal não apresentam esse problema.

Magento ver. 2.4.3-p1

**Comment by r-martins** [comment]
Fala @rodzappa.
Obrigado por reportar o problema.
De fato isso foi contornado no Magento 1 há um tempão, mas nunca foi apontado no M2.
Como o Pagseguro não aceita qtd < 1, tratamos de outra forma.

Vou adicionar ao nosso roadmap.

**Comment by r-martins** [comment]
Contemplado no [Pull Request 106](https://github.com/r-martins/PagSeguro-Magento-Transparente-M2/pull/106).
Deve ser testado e publicado em breve.

**Comment by r-martins** [comment]
Resolvido e publicado na versão 2.13.0.

**Comment by rodzappa** [comment]
@r-martins, obrigado por disponibilizar a correção.
