### ISSUE TITLE
Suporte à pagamentos recorrentes

### ISSUE THREAD

**Issue by rodzappa** [r-martins/PagSeguro-Magento-Transparente-M2#105]
O módulo do PagSeguro para Magento 1.9.x tem a funcionalidade de pagamento recorrente implementada.
Há algum planejamento no roadmap para implementar a mesma funcionalidade para o módulo do Magento 2.x?

**Comment by r-martins** [comment]
Oi, @rodzappa.
No roadmap ainda não existe. Se isso ocorrer será na nova API do PagSeguro e não acontecerá da mesma forma (passiva - onde o PagSeguro é responsável pelas cobranças) como é hoje.
De qualquer forma devemos ter um longo sprint para migrar o módulo para a nova API antes de seguir com novos recursos recursos grandes como este.
