### ISSUE TITLE
Ultima versão do módulo diferente

### ISSUE THREAD

**Issue by michelbrito** [r-martins/PagSeguro-Magento-Transparente-M2#114]
Olá Ricardo,

Tem um problema relacionado a versão do módulo.
Vejo que aqui no git a ultima release é versão 3.14.0.
Já no composer.json está 2.14.0
E no packagist.org 2.13.0

**Comment by r-martins** [comment]
Oi, @michelbrito.
Realmente rolou uma confusão gigante da minha parte na hora de publicar o release.
O módulo para Magento 1 está na versão 3.14.x enquanto o de M2 estava na 2.14.x.
Acabei lançando a 2.14 como 3.14. 
Provavelmente este release será excluído em prol do 2.14.0.

Isso causou algum problema do seu lado ou apenas confusão mesmo?

**Comment by michelbrito** [comment]
@r-martins esse problema deve ter afetado todo mundo..rsrs, pois no composer só puxa a 2.13.0 mas aqui conseguimos resolver colocando os arquivos da release no nosso repo composer privado até que esteja corrigido a release.

Um abraço

**Comment by r-martins** [comment]
Corrigido. :)
Obrigado por avisar, @michelbrito. Tinha passado despercebido até agora.
