### ISSUE TITLE
No pagamento redirecionado (PIX)

### ISSUE THREAD

**Issue by mauricio-tonny** [r-martins/PagSeguro-Magento-Transparente-M2#120]
Ao selecionar apenas opção PIX do pagamento redirecionado (Pagar no PagSeguro), 

Ao inserir item no carrinho estando a opção **Redirecionar para página de sucesso** habilitada, ao avançar para o pagseguro ele zera o carrinho.

É necessário deixar a opção desabilitada, também não é enviado e-mail para o cliente do pedido pendente ou da confirmação do pagamento nesta modalidade.

![Captura de tela de 2022-04-18 17-51-23](https://user-images.githubusercontent.com/68695691/163876427-6455579e-66ad-47c1-ba74-10b941b7012a.png)

**Comment by r-martins** [comment]
Oi, @mauricio-tonny. Tudo bom?
Zerar o carrinho após a finalização do pedido é o comportamento esperado em todo meio de pagamento, afinal o cliente já finalizou o pedido.

Fiz um teste com as mesmas configurações que as suas e não consegui reproduzir o problema.
O email também foi enviado com sucesso.
Note que, se o envio assíncrono do Magento estiver configurado você deve ter o cron ativado.

Veja um vídeo do meu teste em https://capture.dropbox.com/A6spSN7NzJlw4tdS.
