### ISSUE TITLE
Erro com endereço de cobrança.

### ISSUE THREAD

**Issue by birksnet** [r-martins/PagSeguro-Magento-Transparente-M2#121]
Usamos seu modulo para processar pagamentos com a PagSeguro com o checkout transparente com  1 e 2 cartões. estou tendo um erro somente quando o seu modulo esta ativo, em outros métodos de pagamento quando passamos a compra o endereço de entrega vem diferente do endereço de cobrança.  

Preciso que os dois endereços seja iguais! não usamos endereço diferentes para entrega e para cobrança. porem quando o pedido é salvo o endereço de entrega vem correto mas o de cobrança não ( Os campos numero e complemento ) vem com os dados da compra anterior, ou seja a 4ª compra fica com o numero e complemento da 3ª compra.

**Comment by r-martins** [comment]
Oi, @birksnet 
Respondi pra você via chamado por enquanto..
Assim que tiver um retorno por lá, podemos atualizar o ticket aqui também. Seguirei no aguardo do seu retorno. ;)

**Comment by r-martins** [comment]
Ainda em Julho/22 concluimos que o problema se dava em alguma outra customização não relacionada ao módulo de pagamento nem ao módulo de checkout do Ariel/MestreMagento.

A esta altura espero que tenha conseguido resolver, já que não tive seu retorno no ticket após minha última msg em 21/jul/22.

(Ticket 18670).
