### ISSUE TITLE
Métodos pagamento para criação de pedidos no Painel Administrativo

### ISSUE THREAD

**Issue by guiserinoli** [r-martins/PagSeguro-Magento-Transparente-M2#123]
Olá pessoal,

Temos um cliente que gostaria de ter as opções do PagSeguro disponíveis para a criação de pedido no Painel Administrativo. Vimos que a opção de redirecionar paga o Pagseguro funciona, mas as demais não. Algum motivo específico?

**Comment by r-martins** [comment]
Oi, @guiserinoli 
Você deveria conseguir ver as opções de boleto e tef também. Caso não esteja conseguindo, por favor reabra a issue aqui.
O cartão de crédito realmente não é habilitada para evitar que as lojas façam pedidos por telefone, pedindo o cartão do cliente.

**Comment by r-martins** [comment]
PS: lançamos a versão 2.19.0 que agora mostra estas opções no admin. ;)
#ficadica
