### ISSUE TITLE
é compatível com php 8.1?

### ISSUE THREAD

**Issue by davirs** [r-martins/PagSeguro-Magento-Transparente-M2#130]
Olá. Eu instalei para teste mas notei alguns erros. Gostaria de saber se é compatível com PHP 8.1.
Obrigado

![image](https://user-images.githubusercontent.com/4355062/214887802-bf5eb2eb-9a64-4f63-9b43-dfb32192ad6e.png)

**Comment by r-martins** [comment]
Obrigado por reportar.
Foi corrigido na versão 2.21.1.

PS: O módulo suporta php 8.1. Inclusive é o que usamos na nossa [loja demo](https://pagseguro-exemplo-m2.ricardomartins.net.br/).
