### ISSUE TITLE
Instalação do módulo para o Magento 2.3.7

### ISSUE THREAD

**Issue by rmalfer** [r-martins/PagSeguro-Magento-Transparente-M2#135]
Ao instalar o módulo e rodar o compile dá erro e é exibido o erro abaixo:

Compilation was started.
Repositories code generation... 1/8 [===>------------------------]  12% < 1 sec 91.0 MiB
Parse error: syntax error, unexpected '/', expecting function (T_FUNCTION) or const (T_CONST) in /home/wwport/site/app/code/RicardoMartins/PagSeguro/Helper/Data.php on line 93

**Comment by r-martins** [comment]
@rmalfer poderia rodar `php -v` e me dizer que versão está usando do php?

**Comment by r-martins** [comment]
Vi que abriu um chamado, então vou encerrar por aqui e seguimos no seu ticket 19399. ;)
