### ISSUE TITLE
Usar Guzzle como cliente web

### ISSUE THREAD

**Issue by flaviosdev** [r-martins/PagSeguro-Magento-Transparente-M2#136]
Olá, tudo bem?

Perdão se estiver fazendo da forma errada. Ando trabalhando com o módulo de vocês para Magento 2, e percebi que várias chamadas são feitas usando o curl ou o Magento curl. Existe algum motivo? Tive que fazer modificações, e criei clientes com o Guzzle, estou usando e está funcionando perfeitamente. Gostaria de contribuir com essas alterações, e posteriormente adicionar o meu know-how ao módulo. Podemos conversar a respeito?

**Comment by r-martins** [comment]
Oi, @flaviosans . Tudo bom?
Não me recordo do motivo de ter usado o curl direto, mas fique a vontade pra mandar um **[PR](https://github.com/r-martins/PagSeguro-Magento-Transparente-M2/pulls)** com sua contribuição.
Em muitos casos a [gente remunera boas contribuições](https://pagsegurotransparente.zendesk.com/hc/pt-br/articles/208158763) feitas ao modulo. :)

PS: Tem uma versão nova do módulo prestes a ser lançada. Se esperar mais uma ou duas semanas é provável que ela seja divulgada. :)
