### ISSUE TITLE
Erro ao confirmar pagamento!

### ISSUE THREAD

**Issue by KovalskiWeb** [r-martins/PagSeguro-Magento-Transparente-M2#21]
Estou utilizando one step checkout da amasty, e ao clicar em finalizar compra, aparece esse erro: Selected payment method is not available anymore

Só acontece isso com esse método de pagamento do PagSeguro, já testei com outras formas de pagamentos, e funcionou certinho!

**Comment by r-martins** [comment]
Pedi pra Amasty uma copia do OSC deles pra realizar os testes e debugs por aqui.
Vamos aguardar.

**Comment by r-martins** [comment]
A Amasty se negou a enviar a copia do checkout e pediu pro comprador do modulo entrar em contato com o suporte deles a fim de resolver o problema.
