### ISSUE TITLE
Venda com produto duplicado em produtos configuráveis

### ISSUE THREAD

**Issue by iagor4mos** [r-martins/PagSeguro-Magento-Transparente-M2#23]
Ao finalizar a compra e gerar o boleto, o mesmo é gerado com o valor do produto duplicado, no log ele capta o produto configurável e o produto simples associado a ele como dois produtos distintos.

**Comment by r-martins** [comment]
Olá, @iagor4mos.
Receio que o problema seja em outro lugar ou falte algum detalhe nesta desrição.
Fiz o pedido de um item configurável na [loja demo](https://pagseguro-exemplo-m2.ricardomartins.net.br) e o pedido/boleto foi gerado conforme esperado.
Prints abaixo. Por favor me avise se conseguir simular o problema na loja demo e como devo reproduzi-lo.


Finalização do pedido
![Finalizar_Compra](https://user-images.githubusercontent.com/191149/64306050-cf554880-cfd4-11e9-8d66-2af4dad3b282.jpg)

Boleto
![Boleto_-_PagSeguro_UOL](https://user-images.githubusercontent.com/191149/64306081-e5630900-cfd4-11e9-99ee-0c8ff5f6e81a.jpg)

Pedido no admin
![_000000771___Orders___Operations___Sales___Magento_Admin](https://user-images.githubusercontent.com/191149/64306141-0c213f80-cfd5-11e9-9139-bfdf6bf9ad48.jpg)
