### ISSUE TITLE
Pagamento com cartão de credito

### ISSUE THREAD

**Issue by euNatan** [r-martins/PagSeguro-Magento-Transparente-M2#25]
O pagamento com cartão de crédito não é nem processado no magento 2.3, poderia me ajudar?

**Comment by r-martins** [comment]
Oi, @euNatan .
Peço que [abra um chamado](https://pagsegurotransparente.zendesk.com/hc/pt-br/requests/new) pra mim com mais detalhes e o url da loja (se houver).

Vamos manter este canal apenas para reportar bugs. ;)
