### ISSUE TITLE
Não recebo email de pedido

### ISSUE THREAD

**Issue by rafaelstz** [r-martins/PagSeguro-Magento-Transparente-M2#31]
Olá,

Durante meus testes eu não recebo o email transacional nativo do Magento confirmando meu pedido, apenas recebo o email do PagSeguro com o boleto. Tenho todas as opções nativas possibilitando o envio de emails para pedidos e atualizações de pedidos ativas.
Esse é o comportamento nativo do módulo eu ele possibilita o envio do email transacional ao finalizar o pedido?

**Comment by rafaelstz** [comment]
Montei uma instalaçao limpa na mesma instância + sample data e funcionou normalmente.

**Comment by rafaelstz** [comment]
Esse era o erro que eu estava tendo, não relacionado com o módulo.
https://github.com/magento/magento2/issues/25542

**Comment by r-martins** [comment]
Obrigado por pesquisar, debugar e atualizar a issue, @rafaelstz .
