### ISSUE TITLE
Request 15000000141 not found on system.

### ISSUE THREAD

**Issue by rafaelstz** [r-martins/PagSeguro-Magento-Transparente-M2#32]
Estou recebendo essa mensagem abaixo às vezes, falando que não encontra o pedido com o ID da order e às vezes falando que não foi possível cancelar.

<img width="693" alt="Screen Shot 2019-11-11 at 9 32 12 PM" src="https://user-images.githubusercontent.com/610598/68631892-40304980-04cb-11ea-99b6-64a4009473e3.png">

Esse increment ID existe no sistema normalmente.

Estou utilizando PHP 7.1 + Magento 2.3.2

**Comment by r-martins** [comment]
Estranho... Esse erro acontece quando o loadByIncrementId falha ao trazer o pedido.
O único cenário que imagino é: o sistema está tão lento para finalizar o pedido e gravá-lo no banco, que o PagSeguro envia a notificação antes do pedido ser finalizado.
Isso poderia acontecer se durante o fechamento do pedido vc tem alguma integração pesada/lenta, ou o servidor está sobrecarregado.

De uma forma ou de outra, consegue ver se o status que o módulo devolveu pro pagseguro foi status 200? Se for, eu preciso mudar isso pra forçar o pagseguro enviar de novo a notificação.
Consegue confirmar nos [detalhes do pedido no pagseguro](https://pagsegurotransparente.zendesk.com/hc/pt-br/articles/360036087871-Como-posso-saber-se-o-retorno-do-PagSeguro-est%C3%A1-funcionando-)?

**Comment by rafaelstz** [comment]
Sim foi 200 para o PagSeguro, nesse caso é um teste de cartão negado por limite. O server estava lento, acredito que uma solução legal seria utilizar o framework [Guzzle](https://github.com/guzzle/guzzle) e executar os requests que são feitos via CURL através do modo assíncrono com uma promisse para enviar a notificação para o PagSeguro depois do pedido ser concluído.

**Comment by r-martins** [comment]
Oi @rafaelstz.
Bem bacana a ideia. Eu não sabia que o Guzzle fazia isso. Pra mim era só uma alternativa ao curl ou uma classe bonitinha pra fazer requests.
Sei que o M2 tem o guzzle como dependencia, mas não achei nenhum exemplo de uso do guzzle que aguarde o pedido estar concluído.
Não sei nem como poderia testar isso, mas sei q se eu devolver um 503 pra notificação, o PagSeguro vai tentar de novo. Isso já resolveria né. :)

**Comment by rafaelstz** [comment]
Acredito que sim @r-martins, pode usar assincronamente dessa maneira:

```php
$promise = $this->_guzzle->requestAsync('GET', 'http://httpbin.org/get');
$promise->then(function ($response) {
	echo 'Obtive resposta! ' . $response->getStatusCode();
});
```
E se quiser forçar a resposta pode usar o `wait`

```php
$promise = $this->_guzzle->requestAsync('GET', 'http://httpbin.org/get');
$response = $promise->wait();
```

Referência: https://github.com/guzzle/promises#synchronous-wait
