### ISSUE TITLE
Boleto pago vira closed

### ISSUE THREAD

**Issue by rafaelstz** [r-martins/PagSeguro-Magento-Transparente-M2#34]
Ao compensa um boleto o status **pending payment** vai para **closed** ao invés de **processing**.

**Comment by r-martins** [comment]
Isso tinha sido corrigido na 2.3.2. Qual versão está usando Rafa?

**Comment by rafaelstz** [comment]
Estou usando o 2.3.2, o 2.3.3 não rolou por um erro no core.

**Comment by r-martins** [comment]
Tive outro caso deste e já estou testando.
Paguei um boleto no sábado pra testar o problema. Logo devo ter updates.

**Comment by r-martins** [comment]
@rafaelstz estou debruçado neste caso hoje/esta semana e gostaria de matá-lo¹.
Tentei com o caso de outro cliente, mas parecia que o pedido tinha sido cancelado manualmente antes do pagseguro mandar a notificação de pedido pago.
Tentei várias simulações de status de pedido (Magento 2.3.3) e não consegui reproduzir.
Poderia tirar um print do pedido no Magento, e do histórico de status do pedido no PagSeguro?

Obrigado.


¹ me referindo ao caso, não ao @rafaelstz  :)

**Comment by r-martins** [comment]
Alguma novidade @rafaelstz ?
Ainda estou debruçado neste caso. Eu consegui reproduzir no local um cenário parecido, onde o pedido seguiu seu fluxo mas somente os itens de dentro foram cancelados.
![image](https://user-images.githubusercontent.com/191149/71143145-a304c580-226d-11ea-8396-ba2092b8cc51.png)

O problema é que eu só consegui reproduzir uma vez esse comportamento. Eu tenho a base aqui enquanto o pedido estava aguardando pagamento, e reproduzi as notificações de pagamento (que geram invoice) várias vezes, de diversos jeitos, e isso não aconteceu em **nenhuma** das tentativas.
Fiz com e sem opcache, tentei simular o envio em duplicidade da notificação 1 ou 3 (ag pagto e pago), tentei de tudo e não consegui reproduzir.

Se tiver alguma outra pista, por favor compartilhe.

**Comment by r-martins** [comment]
Fim do mistério.
1. [Pedido é alterado para Completo sem ter sido enviado (Geralmente com Boleto)](https://pagsegurotransparente.zendesk.com/hc/pt-br/articles/360038143931-Pedido-%C3%A9-alterado-para-Completo-sem-ter-sido-enviado-Geralmente-com-Boleto-)
2. [Pedidos pagos (ou não) são Cancelados automaticamente](https://pagsegurotransparente.zendesk.com/hc/pt-br/articles/360037776872-Pedidos-pagos-ou-n%C3%A3o-s%C3%A3o-Cancelados-automaticamente)

**Comment by rafaelstz** [comment]
Obrigado pela solução @r-martins
