### ISSUE TITLE
Desativar Foto do Cartao  no Checkout

### ISSUE THREAD

**Issue by pedroohsolucoes** [r-martins/PagSeguro-Magento-Transparente-M2#43]
olá, o modulo tem uma opção quando esta fazendo o pagamento via celular (Mobile) que o cliente pode tirar foto do cartão, porem  gostaria de tirar essa opção, não achei no painel administrador do MAgento2.

Alguém sabe como retirar essa opção?
Essa opção é do modulo Pagseguro ou do Magento2?

Obrigado!

**Comment by r-martins** [comment]
Oi @pedroohsolucoes 
Este é um recurso do celular/navegador e não do módulo.
Pelo que pesquisei este recurso está presente no Safari e Chrome em aparelhos modernos e é exibido em campos de cartão de crédito em sites que possuem https (quase todos e-commerces).
