### ISSUE TITLE
Falha ao obter o token do cartao ou sender_hash

### ISSUE THREAD

**Issue by rafaelcastelani** [r-martins/PagSeguro-Magento-Transparente-M2#45]
2020-04-17 20:53:23] main.DEBUG: "CC validate method" [] []
[2020-04-17 20:53:23] main.DEBUG: Falha ao obter o token do cartao ou sender_hash.
                    Ative o modo debug e observe o console de erros do seu navegador.
                    Se esta for uma atualização via Ajax, ignore esta mensagem até a finalização do pedido.
                    Token do cartão: false/ Sender_hash: false [] []

Estou tendo esse problema no módulo ao instalar no meu site , magento 2.3.2
site Https:www.oneup.com.br

Poderia me ajudar? não consegui passar pagamento via cartão somente boleto , porém o metodo de UpdateHash está dando 200 ...

**Comment by r-martins** [comment]
Olá, @rafaelcastelani . Tudo bom?
Peço que abra uma solicitação [por aqui](https://pagsegurotransparente.zendesk.com/hc/pt-br/requests/new).
Este é o canal onde concentro o suporte (pra não ficar louco rs).
