### ISSUE TITLE
Formas de Recebimento

### ISSUE THREAD

**Issue by rafaelcastelani** [r-martins/PagSeguro-Magento-Transparente-M2#46]
![WhatsApp Image 2020-04-27 at 15 10 10 (1)](https://user-images.githubusercontent.com/2153016/80406914-317ff800-889b-11ea-8b67-a76f6d88d756.jpeg)

Boa tarde Ricardo , não estou achando seu email pra tentar entrar em contato , tenho uma loja m2 , e estou usando seu módulo porém nossas taxas de recebimento e a negociação é bem abaixo como eu faria nesse caso?

**Comment by rafaelcastelani** [comment]
Pode me auxiliar , desde já agradeço muito =)

**Comment by r-martins** [comment]
Oi @rafaelcastelani.
O melhor lugar para entrar em contato comigo sobre **qualquer** assunto relacionado aos módulos PagSeguro é no link abaixo.
https://pagsegurotransparente.zendesk.com/hc/pt-br/requests/new

Com relação a sua dúvida, veja https://pagsegurotransparente.zendesk.com/hc/pt-br/articles/360035615752.

Aguardo seu retorno no primeiro link. ;)
