### ISSUE TITLE
Error parcelamento

### ISSUE THREAD

**Issue by alamengo09** [r-martins/PagSeguro-Magento-Transparente-M2#66]
Nao aparece a opções de parcela na pagina de pagamento do modulo.

![Screenshot from 2020-11-13 14-54-47](https://user-images.githubusercontent.com/59314788/99104932-701f9a80-25c0-11eb-8ffe-a6034739c4d2.png)

**Comment by r-martins** [comment]
Provavelmente é algum problema na configuração do módulo.
Peço que entre em contato em https://pagsegurotransparente.zendesk.com/hc/pt-br.

Certifique-se de ter seguido os passos descritos em https://pagseguro.ricardomartins.net.br/magento2/wizard.html.
