### ISSUE TITLE
Erro js na página de produto - ps_installments_max addEventListener click

### ISSUE THREAD

**Issue by gustavoulyssea** [r-martins/PagSeguro-Magento-Transparente-M2#83]
Fala Canguru!
To atendendo um cliente identifiquei um bug aqui. Apareceu erro em relação ao seguinte código na página de produto.

Este código tá dando erro na execução assíncrona, tá precisando ser executada depois que tudo é renderizado (acredito??)

<script type="application/javascript">
requirejs(['jquery'],function($){
    document.getElementById("ps_installments_max").addEventListener("click", function(event){
        event.preventDefault();
        $('#installments_list').toggle({duration: 500});
    });
});

Da um alô ! Abraço !

**Comment by r-martins** [comment]
só pra me ajudar a reproduzir aqui, você pode me enviar:
1. print de `select * from core_config_data where path like '%pagseguro%'` excluindo o token, email, chave, etc
2. Ctrl+V do conteudo que você tem na `catalog_product_entity_text`  pro atributo de parcelas deste produto (o json das parcelas)

**Comment by r-martins** [comment]
@gustavoulyssea algum update dr?

**Comment by gustavoulyssea** [comment]
@r-martins desculpa deixa eu dar uma bizoiada...

**Comment by gustavoulyssea** [comment]
path                                                             | value                                                                                                                                                                                                                                                                                                                                                                                                    |
payment/rm_pagseguro/sandbox                                     | 1                                                                                                                                                                                                                                                                                                                                                                                                        |
payment/rm_pagseguro/debug                                       | 1                                                                                                                                                                                                                                                                                                                                                                                                        |
payment/rm_pagseguro/send_invoice_email                          | 1                                                                                                                                                                                                                                                                                                                                                                                                        |
payment/rm_pagseguro/customer_cpf_attribute                      | billing|vat_request_success                                                                                                                                                                                                                                                                                                                                                                              |
payment/rm_pagseguro/address_street_attribute                    | street_1                                                                                                                                                                                                                                                                                                                                                                                                 |
payment/rm_pagseguro/address_number_attribute                    | street_2                                                                                                                                                                                                                                                                                                                                                                                                 |
payment/rm_pagseguro/address_complement_attribute                | street_3                                                                                                                                                                                                                                                                                                                                                                                                 |
payment/rm_pagseguro/address_neighborhood_attribute              | street_4                                                                                                                                                                                                                                                                                                                                                                                                 |
payment/rm_pagseguro_cc/active                                   | 0                                                                                                                                                                                                                                                                                                                                                                                                        |
payment/rm_pagseguro_cc/title                                    | PagSeguro UOL                                                                                                                                                                                                                                                                                                                                                                                            |
payment/rm_pagseguro_cc/order_status                             | NULL                                                                                                                                                                                                                                                                                                                                                                                                     |
payment/rm_pagseguro_cc/enable_cc_images                         | 1                                                                                                                                                                                                                                                                                                                                                                                                        |
payment/rm_pagseguro_cc/flag                                     | NULL                                                                                                                                                                                                                                                                                                                                                                                                     |
payment/rm_pagseguro_cc/info_brl                                 | 1                                                                                                                                                                                                                                                                                                                                                                                                        |
payment/rm_pagseguro_cc/owner_dob_attribute                      | is_anonymized                                                                                                                                                                                                                                                                                                                                                                                            |
payment/rm_pagseguro_cc/sort_order                               | NULL                                                                                                                                                                                                                                                                                                                                                                                                     |
payment/rm_pagseguro_cc/group_restriction                        | 0                                                                                                                                                                                                                                                                                                                                                                                                        |
payment/rm_pagseguro_cc/show_total                               | 0                                                                                                                                                                                                                                                                                                                                                                                                        |
payment/rm_pagseguro_cc/force_installments_selection             | 0                                                                                                                                                                                                                                                                                                                                                                                                        |
payment/rm_pagseguro_boleto/active                               | 0                                                                                                                                                                                                                                                                                                                                                                                                        |
payment/rm_pagseguro_boleto/title                                | Boleto - via PagSeguro UOL                                                                                                                                                                                                                                                                                                                                                                               |
payment/rm_pagseguro_boleto/order_status                         | processing                                                                                                                                                                                                                                                                                                                                                                                               |
payment/rm_pagseguro_boleto/sort_order                           | 2                                                                                                                                                                                                                                                                                                                                                                                                        |
payment/rm_pagseguro_tef/active                                  | 0                                                                                                                                                                                                                                                                                                                                                                                                        |
payment/rm_pagseguro_tef/title                                   | PagSeguro - TEF - Ricardo Martins                                                                                                                                                                                                                                                                                                                                                                        |
payment/rm_pagseguro_tef/order_status                            | holded                                                                                                                                                                                                                                                                                                                                                                                                   |
payment/rm_pagseguro_tef/sort_order                              | 3                                                                                                                                                                                                                                                                                                                                                                                                        |
payment/rm_pagseguro_tef/specificcountry                         | NULL                                                                                                                                                                                                                                                                                                                                                                                                     |
payment/rm_pagseguro_pagar_no_pagseguro/active                   | 0                                                                                                                                                                                                                                                                                                                                                                                                        |
payment/rm_pagseguro_pagar_no_pagseguro/redirectURL              | checkout/onepage/success                                                                                                                                                                                                                                                                                                                                                                                 |
payment/rm_pagseguro_pagar_no_pagseguro/title                    | PagSeguro                                                                                                                                                                                                                                                                                                                                                                                                |
payment/rm_pagseguro_pagar_no_pagseguro/description              | Você será redirecionado para o PagSeguro onde poderá escolher a forma de pagamento desejada.                                                                                                                                                                                                                                                                                                             |
payment/rm_pagseguro_pagar_no_pagseguro/order_status             | pending                                                                                                                                                                                                                                                                                                                                                                                                  |
payment/rm_pagseguro_pagar_no_pagseguro/accepted_groups          | CREDIT_CARD,BOLETO                                                                                                                                                                                                                                                                                                                                                                                       |
payment/rm_pagseguro_pagar_no_pagseguro/enable_recovery          | 1                                                                                                                                                                                                                                                                                                                                                                                                        |
payment/rm_pagseguro_pagar_no_pagseguro/disable_frontend         | 0                                                                                                                                                                                                                                                                                                                                                                                                        |
payment/rm_pagseguro_pagar_no_pagseguro/sort_order               | 4                                                                                                                                                                                                                                                                                                                                                                                                        |
payment/rm_pagseguro_pagar_no_pagseguro/redirect_to_success_page | 1                                                                                                                                                                                                                                                                                                                                                                                                        |
payment/rm_pagseguro_cc/show_installments_product_page           | 0                                                                                                                                                                                                                                                                                                                                                                                                        |

**Comment by gustavoulyssea** [comment]
Calma vc ai....

**Comment by gustavoulyssea** [comment]
Desculpa a demora foi dificil chegar ai ... todas as linhas com este atributo tao retornando valor NULL.

**Comment by r-martins** [comment]
Consegue me mandar o Ctrl+V do conteudo que você tem na catalog_product_entity_text pro atributo de parcelas deste produto (o json das parcelas)

**Comment by r-martins** [comment]
@gustavoulyssea  quando puder, reabre esse ticket com os detalhes pra conseguirmos reproduzir aki plz
