### ISSUE TITLE
Loading infinito no checkout e carrinho em branco

### ISSUE THREAD

**Issue by LimaJonas** [r-martins/PagSeguro-Magento-Transparente-M2#86]
Estou com um bug, ou erro. Configurei a versão mais recente do módulo (2.9.6) no Magento 2.3.6, porém quando vou para o carrinho (/checkout/cart) aparece apenas "Consultar Valor do Frete e Imposto" e quando vou direto para o checkout fica um simbolo de loading no canto superior da tela infinitamente.

Se puder me dizer o que posso fazer, ou o motivo do bug, ficaria agradecido.

**Comment by LimaJonas** [comment]
É necessário que o site seja HTTPS? se for, talvez seja esse o problema

**Comment by r-martins** [comment]
Não precisa ser https não.
A menos que você tenha uma mensagem de erro em algum lugar apontando pro meu módulo, é bem provável que o problema seja em outro lugar.
Há uma dezena de outros fatores que podem ocasionar o comportamento que reportou acima, Lima.
Me avise se houver uma forma certa de reproduzir isso em uma loja sem outros módulos.

**Comment by rodrigoobiassi** [comment]
Tive o mesmo problema:
![Screen Shot 2021-06-05 at 14 01 07](https://user-images.githubusercontent.com/14968349/120899529-89dd0980-c606-11eb-9351-00c6c86fa911.png)

Ao desabilitar o módulo "RicardoMartins_PagSeguro" tudo volta a funcionar.
Estou tentando desabilitar outros módulos de terceiros para identificar algum possível conflito.

**Comment by rodrigoobiassi** [comment]
Encontrei o problema e a possível solução. Passos para reprodução:

- Versão do Magento testada: **2.3.6**
- Baixei a última versão do módulo (05/06/2021): **2.9.8**

O problema acontecce aqui causando o checkout/cart com tela branca: $block->getSerializedCheckoutConfig()

vendor/magento/module-checkout/view/frontend/templates/cart/shipping.phtml
![Screen Shot 2021-06-05 at 15 15 55](https://user-images.githubusercontent.com/14968349/120901393-f230e880-c610-11eb-940e-1b360bfda750.png)

Percorrendo o problema, chegamos até o getConfig: $this->configProviders

vendor/magento/module-checkout/Model/CompositeConfigProvider.php
![Screen Shot 2021-06-05 at 15 19 44](https://user-images.githubusercontent.com/14968349/120901472-7daa7980-c611-11eb-9c51-83df8af562c0.png)

vendor/ricardomartins/pagseguro/etc/frontend/di.xml:13
1 - ![Screen Shot 2021-06-05 at 15 20 34](https://user-images.githubusercontent.com/14968349/120901509-c7935f80-c611-11eb-84bf-02f4f6170052.png)

2 - RicardoMartins\PagSeguro\Model\ConfigProvider não existe e tem uma barra invertida no xml
![Screen Shot 2021-06-05 at 15 22 26](https://user-images.githubusercontent.com/14968349/120901519-e09c1080-c611-11eb-84b4-3fcc5581aaea.png)

**Comment by r-martins** [comment]
Correção sugerida pelo @rodrigoobiassi acaba de ser disponibilizada na versão 2.9.9 do módulo.
@LimaJonas, se puder testar aí do seu lado, eu agradeço. ;)
