### ISSUE TITLE
Ajuda para parcela minima

### ISSUE THREAD

**Issue by ricardopantani** [r-martins/PagSeguro-Magento-Transparente-M2#87]
Olá. 
Preciso de ajuda para limitar o valor da parcela mínima. 
Gostaria de limitar o valor das parcelas para um valor mínimo ex. R$30.

**Comment by r-martins** [comment]
Oi @ricardopantani 
Este canal é destinado a reporte de erros no módulo.
Para dúvidas, sugestões, e outros assuntos, peço que use [este formulário](https://pagsegurotransparente.zendesk.com/hc/pt-br/requests/new).

Obrigado pela compreensão.
